apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secretstore
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: infra-iac-gke-gcp
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: eso-sa
            namespace: external-secrets
