apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-release-production
data:
  backendImage: europe-west1-docker.pkg.dev/infra-iac-gke-gcp/apps/backend:latest
  frontendImage: europe-west1-docker.pkg.dev/infra-iac-gke-gcp/apps/frontend:latest
